services:
  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: restdb
      MYSQL_USER: restadmin
      MYSQL_PASSWORD: password
    expose:
      - "3306"
    networks:
      - spring-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      timeout: 20s
      retries: 10

  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    expose:
      - "27017"
    networks:
      - spring-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      timeout: 20s
      retries: 10

  auth-server:
    container_name: auth-server
    image: spring-6-auth-server:0.0.1-SNAPSHOT
    expose:
      - "9000"
    networks:
      - spring-network

  rest-mvc:
    container_name: rest-mvc
    image: spring-6-rest-mvc:0.0.1-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: localmysql
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/restdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://auth-server:9000
      SERVER_PORT: 8080
    expose:
      - "8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - spring-network

  reactive:
    container_name: reactive
    image: spring-6-reactive:0.0.1-SNAPSHOT
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://auth-server:9000 \
      SERVER_PORT: 8080
    expose:
      - "8080"
    networks:
      - spring-network

  reactive-mongo:
    container_name: reactive-mongo
    image: spring-6-reactive-mongo:0.0.1-SNAPSHOT
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://auth-server:9000
      SERVER_PORT: 8080
    expose:
      - "8080"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - spring-network

  gateway:
    container_name: gateway
    image: spring-6-gateway:0.0.1-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://auth-server:9000
    ports:
      - "8080:8080"
    depends_on:
      - auth-server
      - rest-mvc
      - reactive
      - reactive-mongo
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge